# Generated by Django 4.1.5 on 2023-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_campaigns_product_campaigns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='campaigns',
        ),
        migrations.AddField(
            model_name='product',
            name='campaigns',
            field=models.ManyToManyField(blank=True, null=True, to='product.campaigns'),
        ),
    ]
