# Generated by Django 4.1.5 on 2023-01-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_campaigns_product_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='product.campaigns'),
        ),
    ]
