# Generated by Django 4.1.5 on 2023-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_order_amount_order_is_it_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_it_paid',
            field=models.BooleanField(default=False, verbose_name='Ödeme Durumu'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='shopcart',
        ),
        migrations.AddField(
            model_name='order',
            name='shopcart',
            field=models.ManyToManyField(null=True, to='order.shopcart'),
        ),
    ]
